# Generated by Django 5.2.7 on 2025-10-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matricule', models.CharField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('post_name', models.CharField(blank=True, default='', max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10)),
                ('role', models.CharField(choices=[('pdg', 'Président Directeur Général (PDG)'), ('dg', 'Directeur Général (DG)'), ('sga', 'Secrétaire Général Académique (SGA)'), ('sgad', 'Secrétaire Général Administratif (SGAD)'), ('chef_section', 'Chef de Section'), ('chef_departement', 'Chef de Département'), ('professeur', 'Professeur'), ('assistant', 'Assistant'), ('apparitorat', 'Apparitorat'), ('caisse', 'Caisse/Comptabilité'), ('service_it', 'Service IT'), ('etudiant', 'Étudiant'), ('bibliothecaire', 'Bibliothécaire'), ('jury', 'Jury')], default='etudiant', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Activé'), ('inactive', 'Inactif'), ('pending', 'En attente'), ('suspended', 'Suspendu')], default='pending', max_length=20)),
                ('team_status', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_status', models.CharField(choices=[('en_cours', 'En cours'), ('reussi', 'Réussi'), ('non_reussi', 'Non réussi')], default='en_cours', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('current_auditoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='academics.auditoire')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('previous_auditoires', models.ManyToManyField(blank=True, related_name='previous_users', to='academics.auditoire')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
