# Generated by Django 5.2.7 on 2025-10-23 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_academicprofile_studentprofile_paiement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='postnom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='postnom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=10),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pdg', 'PDG'), ('directeur_general', 'Directeur Général'), ('sga', 'Secrétariat Général Académique (SGA)'), ('sgad', 'Secrétariat Général Adjoint (SGAD)'), ('chef_section', 'Chef de Section'), ('chef_departement', 'Chef de Département'), ('enseignant', 'Enseignant (Titulaire)'), ('assistant', 'Assistant'), ('apparitorat', 'Apparitorat'), ('caisse', 'Caisse/Comptabilité'), ('service_it', 'Service IT'), ('etudiant', 'Étudiant'), ('bibliothecaire', 'Bibliothécaire'), ('jury', 'Jury')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
