# Generated by Django 5.2.7 on 2025-10-31 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_courseassignment_unique_together'),
        ('accounts', '0002_user_section_head_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_head_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='academics.departement'),
        ),
    ]
