# Generated by Django 5.2.7 on 2025-10-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_academicprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
