# Generated by Django 5.2.7 on 2025-10-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_academicprofile_office_academicprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprofile',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
