# Generated by Django 5.2.7 on 2025-10-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=10, help_text='La note maximale pour ce devoir'),
        ),
    ]
