# Generated by Django 5.2.7 on 2025-10-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_academicprofile_full_name_and_more'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Durée du quiz en minutes'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__role__role': 'assistant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.academicprofile'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__role__role': 'assistant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.academicprofile'),
        ),
    ]
