# Generated by Django 5.2.7 on 2025-10-30 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_assignment_total_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['assistant', 'professeur']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='assistant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['assistant', 'professeur']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=10, help_text='La note maximale pour ce quiz'),
        ),
    ]
