# Generated by Django 5.2.7 on 2025-10-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_quiz_duration_alter_assignment_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(choices=[('TP', 'Travail Pratique'), ('TD', 'Travail Dirigé')], default='TP', max_length=2),
        ),
    ]
