# Generated by Django 5.2.7 on 2025-10-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_assignment_assistant_alter_quiz_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
