# Generated by Django 5.2.7 on 2025-10-24 12:09

from django.db import migrations, models

def migrate_description_to_questionnaire(apps, schema_editor):
    Assignment = apps.get_model('evaluations', 'Assignment')
    for assignment in Assignment.objects.all():
        if assignment.description_old:
            assignment.questionnaire = [{'type': 'text', 'question': assignment.description_old, 'points': 20}]
            assignment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_assignment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='questionnaire',
            new_name='description_old',
        ),
        migrations.AddField(
            model_name='assignment',
            name='questionnaire',
            field=models.JSONField(default=list, help_text="Liste de questions pour le devoir"),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=20, help_text="La note maximale pour ce devoir"),
        ),
        migrations.RunPython(migrate_description_to_questionnaire, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='assignment',
            name='description_old',
        ),
    ]
