# Generated by Django 5.2.7 on 2025-10-26 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_academicprofile_office_and_more'),
        ('evaluations', '0004_assignment_total_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='submitted_at',
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='evaluations.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'quiz')},
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.quizattempt'),
        ),
    ]
