# Generated by Django 5.2.7 on 2025-10-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_submission_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
