# Generated by Django 5.2.7 on 2025-10-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_remove_answer_student_remove_answer_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.quizattempt'),
        ),
    ]
