# Generated by Django 5.2.7 on 2025-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_answer_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='submission_reason',
            field=models.CharField(choices=[('manual', 'Manuel'), ('time-out', 'Temps écoulé'), ('left-page', 'Page quittée')], default='left-page', max_length=10),
        ),
    ]
