# Generated by Django 5.2.8 on 2025-11-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_quizattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='submission_reason',
            field=models.CharField(choices=[('manual', 'Manuel'), ('time-out', 'Temps écoulé'), ('left-page', 'Page quittée')], default='manual', max_length=10),
        ),
    ]
