# Generated by Django 5.2.8 on 2025-11-27 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_quizsubmission_submission_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis')], default='en_cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
