# Generated by Django 5.2.7 on 2025-10-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_quizattempt_submission_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, help_text="Contenu de la soumission de l'étudiant"),
        ),
    ]
