# Generated by Django 5.2.7 on 2025-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_submission_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=20, help_text='La note maximale pour ce quiz'),
        ),
    ]
