# Generated by Django 5.2.7 on 2025-10-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_quiz_total_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='submission_reason',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis pour correction'), ('noté', 'Noté')], default='en_cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
