# Generated by Django 5.2.7 on 2025-10-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_remove_quizattempt_submission_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='graded_at',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='status',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='submission_reason',
            field=models.CharField(choices=[('manual', 'Manuel'), ('time-out', 'Temps écoulé'), ('left-page', 'Page quittée')], default='left-page', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
