# Generated by Django 5.2.7 on 2025-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_remove_quizattempt_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='correction_status',
            field=models.CharField(choices=[('automatic', 'Automatique'), ('manual', 'Manuel'), ('pending', 'En attente')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points_obtained',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
