# Generated by Django 5.2.7 on 2025-10-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Ex: 1 pour Licence 1, 2 pour Licence 2, etc.')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Assignation de cours',
                'verbose_name_plural': 'Assignations de cours',
            },
        ),
        migrations.CreateModel(
            name='CourseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tranche_number', models.PositiveSmallIntegerField(choices=[(1, '1ère tranche'), (2, '2ème tranche'), (3, '3ème tranche')], default=1)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('auditoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='academics.auditoire')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
                ('session_type', models.CharField(choices=[('mi-session', 'Mi-Session'), ('session', 'Session')], default='session', max_length=20)),
                ('auditoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.auditoire')),
            ],
        ),
        migrations.CreateModel(
            name='MiSessionCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Cours de Mi-Session',
                'verbose_name_plural': 'Cours de Mi-Session',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.course',),
        ),
        migrations.CreateModel(
            name='SessionCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Cours de Session',
                'verbose_name_plural': 'Cours de Session',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.course',),
        ),
    ]
