# Generated by Django 5.2.7 on 2025-10-30 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='assistant',
            field=models.ForeignKey(limit_choices_to={'role__in': ['assistant', 'professeur']}, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_by_assistant', to='academics.course'),
        ),
        migrations.AddField(
            model_name='coursemessage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='academics.course'),
        ),
        migrations.AddField(
            model_name='coursemessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_course_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoire',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoires', to='academics.departement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departement',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academics.section'),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('assistant', 'course')},
        ),
    ]
