# Generated by Django 5.2.7 on 2025-10-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('pdg', 'PDG'), ('directeur_general', 'Directeur Général'), ('sga', 'Secrétariat Général Académique (SGA)'), ('sgad', 'Secrétariat Général Adjoint (SGAD)'), ('chef_section', 'Chef de Section'), ('chef_departement', 'Chef de Département'), ('enseignant', 'Enseignant (Titulaire)'), ('assistant', 'Assistant'), ('apparitorat', 'Apparitorat'), ('caisse', 'Caisse/Comptabilité'), ('service_it', 'Service IT'), ('etudiant', 'Étudiant'), ('bibliothecaire', 'Bibliothécaire'), ('jury', 'Jury')], max_length=50),
        ),
    ]
