# Generated by Django 5.2.7 on 2025-10-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course',)},
        ),
    ]
