# Generated by Django 5.2.7 on 2025-10-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_role_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='auditoire',
        ),
    ]
