# Generated by Django 5.2.7 on 2025-10-31 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_courseassignment_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='heads',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'chef_departement'}, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
