# Generated by Django 5.2.7 on 2025-10-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_role_auditoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='session_type',
            field=models.CharField(choices=[('mi-session', 'Mi-Session'), ('session', 'Session')], default='session', max_length=20),
        ),
    ]
