# Generated by Django 5.2.7 on 2025-10-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_course_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiSessionCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Cours de Mi-Session',
                'verbose_name_plural': 'Cours de Mi-Session',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.course',),
        ),
        migrations.CreateModel(
            name='SessionCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Cours de Session',
                'verbose_name_plural': 'Cours de Session',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.course',),
        ),
        migrations.AlterField(
            model_name='course',
            name='session_type',
            field=models.CharField(choices=[('mi-session', 'Mi-Session'), ('session', 'Session')], max_length=20),
        ),
    ]
