# Generated by Django 5.2.7 on 2025-10-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_departement_heads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='heads',
        ),
    ]
