# Generated by Django 5.2.7 on 2025-11-01 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_departement_heads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendrier',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='academics.course'),
        ),
        migrations.AddField(
            model_name='calendrier',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['assistant', 'professeur']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
