# Generated by Django 5.2.7 on 2025-10-23 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_misessioncourse_sessioncourse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='tranche_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1ère tranche'), (2, '2ème tranche'), (3, '3ème tranche')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='session_type',
            field=models.CharField(choices=[('mi-session', 'Mi-Session'), ('session', 'Session')], default='session', max_length=20),
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('description', models.TextField(blank=True)),
                ('academic_status', models.CharField(choices=[('en_cours', 'En cours'), ('reussi', 'Réussi'), ('non_reussi', 'Non réussi')], default='en_cours', max_length=20)),
                ('current_auditoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='academics.auditoire')),
                ('previous_auditoires', models.ManyToManyField(blank=True, related_name='previous_students', to='academics.auditoire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='paiement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.studentprofile'),
        ),
    ]
