# Generated by Django 5.2.7 on 2025-10-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_paiement_tranche_number_alter_course_session_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_auditoire',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='previous_auditoires',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AcademicProfile',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
