# Generated by Django 5.2.7 on 2025-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_calendrier_course_calendrier_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendrier',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calendrier',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='calendrier',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='calendrier',
            name='title',
        ),
        migrations.AddField(
            model_name='calendrier',
            name='day',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], default='Lundi', max_length=10),
        ),
        migrations.AddField(
            model_name='calendrier',
            name='end_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='calendrier',
            name='session_type',
            field=models.CharField(choices=[('mi-session', 'Mi-Session'), ('session', 'Session')], default='session', max_length=20),
        ),
        migrations.AddField(
            model_name='calendrier',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
