# Generated by Django 5.2.7 on 2025-10-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_remove_paiement_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
