# Generated by Django 5.2.7 on 2025-10-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_delete_role'),
        ('accounts', '0003_remove_academicprofile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(limit_choices_to={'user__role__role': 'assistant'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='accounts.academicprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_by_assistant', to='academics.course')),
            ],
            options={
                'verbose_name': 'Assignation de cours',
                'verbose_name_plural': 'Assignations de cours',
                'unique_together': {('assistant', 'course')},
            },
        ),
    ]
