# Generated by Django 5.2.7 on 2025-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_courseassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoire',
            options={'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='auditoire',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Ex: 1 pour Licence 1, 2 pour Licence 2, etc.'),
        ),
    ]
