# Generated by Django 5.2.7 on 2025-10-24 08:02

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Course = apps.get_model('academics', 'Course')
    for row in Course.objects.all():
        row.code = str(uuid.uuid4())[:8].upper()
        row.save(update_fields=['code'])

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_coursemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
