# Generated by Django 5.2.7 on 2025-10-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
