# Generated by Django 5.2.7 on 2025-10-30 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_courseassignment_unique_together'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='auditorium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorium_messages', to='academics.auditoire'),
        ),
    ]
